import {
  User,
  Client,
  Project,
  WBSItem,
  CostRecord,
  SiteReport,
  ProjectHistory,
  SystemSettings,
  AuditLog,
  ProjectDocument,
  EmailAlert,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin',
    name: 'Sarah Jenkins',
    username: 'admin',
    email: 'sarah.jenkins@buildiq.ca',
    role: 'admin',
    department: 'Governance & Administration',
    password: 'password123',
    status: 'active',
    phone: '+1 (416) 555-0101',
    created_at: '2025-01-15T08:00:00Z',
  },
  {
    id: 'usr_pm',
    name: 'David Chen',
    username: 'pm',
    email: 'david.chen@buildiq.ca',
    role: 'pm',
    department: 'Project Operations',
    password: 'password123',
    status: 'active',
    phone: '+1 (416) 555-0102',
    created_at: '2025-01-16T09:00:00Z',
  },
  {
    id: 'usr_eng',
    name: 'Alex Rivera',
    username: 'engineer',
    email: 'alex.rivera@buildiq.ca',
    role: 'engineer',
    department: 'Engineering & Technical Services',
    password: 'password123',
    status: 'active',
    phone: '+1 (416) 555-0106',
    created_at: '2025-01-20T10:00:00Z',
  },
  {
    id: 'usr_fin',
    name: 'Elena Rostova',
    username: 'finance',
    email: 'elena.rostova@buildiq.ca',
    role: 'finance',
    department: 'Corporate Finance & Cost Control',
    password: 'password123',
    status: 'active',
    phone: '+1 (416) 555-0107',
    created_at: '2025-01-22T11:00:00Z',
  },
  {
    id: 'usr_sup',
    name: "Liam O'Connor",
    username: 'supervisor',
    email: 'liam.oconnor@buildiq.ca',
    role: 'engineer',
    department: 'Site Supervision & Field Engineering',
    password: 'password123',
    status: 'active',
    phone: '+1 (416) 555-0103',
    created_at: '2025-02-01T08:30:00Z',
  },
  {
    id: 'usr_estimator',
    name: 'Rachel Torres',
    username: 'estimator',
    email: 'rachel.torres@buildiq.ca',
    role: 'finance',
    department: 'Cost Estimation & Quantity Surveying',
    password: 'password123',
    status: 'active',
    phone: '+1 (416) 555-0104',
    created_at: '2025-02-05T10:15:00Z',
  },
  {
    id: 'usr_safety',
    name: 'Michael Thorne',
    username: 'safety',
    email: 'michael.thorne@buildiq.ca',
    role: 'engineer',
    department: 'HSE & Safety Engineering',
    password: 'password123',
    status: 'active',
    phone: '+1 (416) 555-0105',
    created_at: '2025-02-10T11:00:00Z',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli_1',
    name: 'Apex Urban Developments',
    contact: 'Marcus Vance',
    email: 'marcus@apexurban.ca',
    phone: '+1 (416) 555-0192',
    company: 'Apex Urban Group',
  },
  {
    id: 'cli_2',
    name: 'Skyline Commercial Holdings',
    contact: 'Brenda Miller',
    email: 'brenda.m@skylineholdings.ca',
    phone: '+1 (604) 555-0144',
    company: 'Skyline Commercial',
  },
  {
    id: 'cli_3',
    name: 'Maple Ridge Residential Partners',
    contact: 'Jean-Luc Tremblay',
    email: 'jtremblay@mapleridge.ca',
    phone: '+1 (403) 555-0183',
    company: 'Maple Ridge Capital',
  },
  {
    id: 'cli_4',
    name: 'Horizon Retail Properties',
    contact: 'Sofia Al-Hassan',
    email: 'sofia@horizonretail.ca',
    phone: '+1 (514) 555-0167',
    company: 'Horizon Real Estate',
  },
  {
    id: 'cli_5',
    name: 'Metro Health & Institutional',
    contact: 'Dr. Gregory Palmer',
    email: 'gpalmer@metrohealthinfra.ca',
    phone: '+1 (613) 555-0128',
    company: 'Metro Institutional Trust',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  // 2 ACTIVE PROJECTS
  {
    id: 'proj_act_1',
    project_number: 'PRJ-2026-001',
    name: 'Riverside Modern Condominiums',
    client_id: 'cli_1',
    type: 'Residential',
    building_type: 'Apartment',
    location: 'Toronto, ON',
    floor_area: 600,
    floors: 3,
    contract_value: 1200000,
    approved_budget: 950000,
    start_date: '2026-03-01',
    planned_completion: '2026-11-30',
    project_manager: 'David Chen',
    description: '3-storey residential multi-unit apartment complex featuring modern reinforced concrete frame, high-efficiency envelope, and luxury interior finishes.',
    status: 'Active',
    forecast_remaining: 520000,
    progress: 45,
    created_at: '2026-02-15T09:00:00Z',
  },
  {
    id: 'proj_act_2',
    project_number: 'PRJ-2026-002',
    name: 'Centennial Corporate HQ Refit',
    client_id: 'cli_2',
    type: 'Commercial',
    building_type: 'Office Renovation',
    location: 'Ottawa, ON',
    floor_area: 1200,
    floors: 4,
    contract_value: 2400000,
    approved_budget: 1950000,
    start_date: '2026-01-15',
    planned_completion: '2026-09-15',
    project_manager: 'Sarah Jenkins',
    description: 'Complete seismic upgrade, interior demolition, open-plan structural alterations, and state-of-the-art acoustic partitions.',
    status: 'Active',
    forecast_remaining: 680000,
    progress: 70,
    created_at: '2026-01-05T10:00:00Z',
  },

  // 1 PLANNING PROJECT
  {
    id: 'proj_plan_1',
    project_number: 'PRJ-2026-004',
    name: 'Bloor West Medical Pavilion',
    client_id: 'cli_5',
    type: 'Institutional',
    building_type: 'Clinic / Medical Office',
    location: 'Toronto, ON',
    floor_area: 850,
    floors: 3,
    contract_value: 2100000,
    approved_budget: 1700000,
    start_date: '2026-10-01',
    planned_completion: '2027-06-30',
    project_manager: 'David Chen',
    description: 'State-of-the-art outpatient clinical suite with reinforced lead-lined diagnostic labs, HVAC medical air scrubbers, and accessible elevator.',
    status: 'Planning',
    forecast_remaining: 1700000,
    progress: 0,
    created_at: '2026-06-01T11:00:00Z',
  },

  // 1 COMPLETED HISTORICAL / BENCHMARK PROJECT (Total 4 Demo Projects: 2 Active, 1 Planning, 1 Completed)
  {
    id: 'proj_hist_1',
    project_number: 'PRJ-2024-001',
    name: 'Highland Residences Phase 1',
    client_id: 'cli_1',
    type: 'Residential',
    building_type: 'Townhouse',
    location: 'Toronto, ON',
    floor_area: 580,
    floors: 3,
    contract_value: 1180000,
    approved_budget: 960000,
    start_date: '2024-02-01',
    planned_completion: '2024-10-15',
    actual_completion: '2024-10-20',
    project_manager: 'David Chen',
    description: 'Multi-family residential complex with underground parking, insulated concrete forms (ICF), and bespoke millwork.',
    status: 'Completed',
    forecast_remaining: 0,
    progress: 100,
    created_at: '2024-01-10T08:00:00Z',
  },
];

// 5 VERIFIED ARCHIVE BENCHMARK PROJECTS (Residential, Commercial, Retail across Ontario)
export const INITIAL_PROJECT_HISTORY: ProjectHistory[] = [
  {
    id: 'hist_1',
    project_id: 'proj_hist_1',
    project_name: 'Highland Residences Phase 1',
    client_name: 'Apex Urban Developments',
    project_type: 'Residential',
    building_type: 'Townhouse',
    location: 'Toronto, ON',
    floor_area: 580,
    floors: 3,
    contract_value: 1180000,
    final_cost: 998000,
    completion_year: 2024,
    duration_weeks: 37,
    labour_cost: 280000,
    material_cost: 485000,
    subcontractor_cost: 165000,
    equipment_cost: 48000,
    other_cost: 20000,
    profit: 182000,
    margin: 15.42,
    cost_per_m2: 1720.69,
    contract_value_per_m2: 2034.48,
    completed_date: '2024-10-20',
  },
  {
    id: 'hist_2',
    project_id: 'proj_hist_2',
    project_name: 'Bayview Luxury Condos',
    client_name: 'Maple Ridge Residential Partners',
    project_type: 'Residential',
    building_type: 'Apartment',
    location: 'Toronto, ON',
    floor_area: 650,
    floors: 4,
    contract_value: 1350000,
    final_cost: 1170000,
    completion_year: 2024,
    duration_weeks: 34,
    labour_cost: 320000,
    material_cost: 590000,
    subcontractor_cost: 180000,
    equipment_cost: 55000,
    other_cost: 25000,
    profit: 180000,
    margin: 13.33,
    cost_per_m2: 1800.0,
    contract_value_per_m2: 2076.92,
    completed_date: '2024-12-05',
  },
  {
    id: 'hist_3',
    project_id: 'proj_hist_3',
    project_name: 'Queen Street Boutique Flats',
    client_name: 'Apex Urban Developments',
    project_type: 'Residential',
    building_type: 'Apartment',
    location: 'Toronto, ON',
    floor_area: 610,
    floors: 4,
    contract_value: 1260000,
    final_cost: 1110200,
    completion_year: 2025,
    duration_weeks: 33,
    labour_cost: 310000,
    material_cost: 565000,
    subcontractor_cost: 160000,
    equipment_cost: 52000,
    other_cost: 23200,
    profit: 149800,
    margin: 11.89,
    cost_per_m2: 1820.0,
    contract_value_per_m2: 2065.57,
    completed_date: '2025-09-02',
  },
  {
    id: 'hist_4',
    project_id: 'proj_hist_4',
    project_name: 'Yorkville Creative Studios',
    client_name: 'Skyline Commercial Holdings',
    project_type: 'Commercial',
    building_type: 'Office Renovation',
    location: 'Toronto, ON',
    floor_area: 450,
    floors: 2,
    contract_value: 850000,
    final_cost: 720000,
    completion_year: 2025,
    duration_weeks: 23,
    labour_cost: 215000,
    material_cost: 340000,
    subcontractor_cost: 115000,
    equipment_cost: 32000,
    other_cost: 18000,
    profit: 130000,
    margin: 15.29,
    cost_per_m2: 1600.0,
    contract_value_per_m2: 1888.89,
    completed_date: '2025-08-10',
  },
  {
    id: 'hist_5',
    project_id: 'proj_hist_5',
    project_name: 'St. Clair Plaza Retail Units',
    client_name: 'Horizon Retail Properties',
    project_type: 'Retail',
    building_type: 'Commercial Strip',
    location: 'Toronto, ON',
    floor_area: 800,
    floors: 1,
    contract_value: 1400000,
    final_cost: 1160000,
    completion_year: 2025,
    duration_weeks: 28,
    labour_cost: 310000,
    material_cost: 590000,
    subcontractor_cost: 180000,
    equipment_cost: 56000,
    other_cost: 24000,
    profit: 240000,
    margin: 17.14,
    cost_per_m2: 1450.0,
    contract_value_per_m2: 1750.0,
    completed_date: '2025-12-12',
  },
];

// WBS items for Riverside Modern Condominiums (proj_act_1)
export const INITIAL_WBS_ITEMS: WBSItem[] = [
  // Phase 01: Preliminaries
  {
    id: 'wbs_phase_1',
    project_id: 'proj_act_1',
    parent_id: null,
    is_phase: true,
    phase_code: '01',
    wbs_code: '01',
    name: '01 — Preliminaries',
    description: 'Mobilization, permits, safety, site logistics',
    start_date: '2026-03-01',
    end_date: '2026-03-20',
    planned_cost: 75000,
    actual_cost: 72400,
    progress: 100,
    status: 'Completed',
  },
  {
    id: 'wbs_act_1_1',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_1',
    is_phase: false,
    wbs_code: '01.01',
    name: 'Mobilization',
    description: 'Site office, temporary utilities, perimeter hoarding',
    start_date: '2026-03-01',
    end_date: '2026-03-10',
    planned_cost: 40000,
    actual_cost: 38200,
    progress: 100,
    status: 'Completed',
  },
  {
    id: 'wbs_act_1_2',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_1',
    is_phase: false,
    wbs_code: '01.02',
    name: 'Site Establishment & Safety',
    description: 'Security fencing, first aid stations, signages',
    start_date: '2026-03-11',
    end_date: '2026-03-20',
    planned_cost: 35000,
    actual_cost: 34200,
    progress: 100,
    status: 'Completed',
  },

  // Phase 02: Foundation
  {
    id: 'wbs_phase_2',
    project_id: 'proj_act_1',
    parent_id: null,
    is_phase: true,
    phase_code: '02',
    wbs_code: '02',
    name: '02 — Foundation',
    description: 'Excavation, earthworks, blinding, footing reinforcement & concrete',
    start_date: '2026-03-21',
    end_date: '2026-05-15',
    planned_cost: 210000,
    actual_cost: 206500,
    progress: 100,
    status: 'Completed',
  },
  {
    id: 'wbs_act_2_1',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_2',
    is_phase: false,
    wbs_code: '02.01',
    name: 'Excavation & Shoring',
    description: 'Bulk soil removal and perimeter trenching',
    start_date: '2026-03-21',
    end_date: '2026-04-05',
    planned_cost: 65000,
    actual_cost: 64100,
    progress: 100,
    status: 'Completed',
  },
  {
    id: 'wbs_act_2_2',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_2',
    is_phase: false,
    wbs_code: '02.02',
    name: 'Blinding & Waterproofing',
    description: 'Sub-base levelling and membrane barrier',
    start_date: '2026-04-06',
    end_date: '2026-04-18',
    planned_cost: 35000,
    actual_cost: 33800,
    progress: 100,
    status: 'Completed',
  },
  {
    id: 'wbs_act_2_3',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_2',
    is_phase: false,
    wbs_code: '02.03',
    name: 'Reinforcement (Rebar Caging)',
    description: 'Grade 60 deformed rebar layout for footings and pads',
    start_date: '2026-04-19',
    end_date: '2026-04-30',
    planned_cost: 50000,
    actual_cost: 49800,
    progress: 100,
    status: 'Completed',
  },
  {
    id: 'wbs_act_2_4',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_2',
    is_phase: false,
    wbs_code: '02.04',
    name: 'Concrete Pouring & Curing',
    description: '35 MPa ready-mix concrete pouring for base slabs',
    start_date: '2026-05-01',
    end_date: '2026-05-15',
    planned_cost: 60000,
    actual_cost: 58800,
    progress: 100,
    status: 'Completed',
  },

  // Phase 03: Structure
  {
    id: 'wbs_phase_3',
    project_id: 'proj_act_1',
    parent_id: null,
    is_phase: true,
    phase_code: '03',
    wbs_code: '03',
    name: '03 — Structure',
    description: 'Columns, suspended beams, precast hollow core and suspended slabs',
    start_date: '2026-05-16',
    end_date: '2026-07-31',
    planned_cost: 290000,
    actual_cost: 148100,
    progress: 55,
    status: 'In Progress',
  },
  {
    id: 'wbs_act_3_1',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_3',
    is_phase: false,
    wbs_code: '03.01',
    name: 'Columns & Shear Walls',
    description: 'Level 1 & 2 reinforced structural vertical load columns',
    start_date: '2026-05-16',
    end_date: '2026-06-15',
    planned_cost: 105000,
    actual_cost: 98400,
    progress: 100,
    status: 'Completed',
  },
  {
    id: 'wbs_act_3_2',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_3',
    is_phase: false,
    wbs_code: '03.02',
    name: 'Beams & Lintels',
    description: 'Horizontal load transfer framing',
    start_date: '2026-06-16',
    end_date: '2026-07-10',
    planned_cost: 85000,
    actual_cost: 49700,
    progress: 60,
    status: 'In Progress',
  },
  {
    id: 'wbs_act_3_3',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_3',
    is_phase: false,
    wbs_code: '03.03',
    name: 'Upper Slabs Pouring',
    description: 'Level 3 & roof deck slab shuttering and pour',
    start_date: '2026-07-11',
    end_date: '2026-07-31',
    planned_cost: 100000,
    actual_cost: 0,
    progress: 0,
    status: 'Not Started',
  },

  // Phase 04: Blockwork
  {
    id: 'wbs_phase_4',
    project_id: 'proj_act_1',
    parent_id: null,
    is_phase: true,
    phase_code: '04',
    wbs_code: '04',
    name: '04 — Blockwork',
    description: 'External masonry cavity walls and internal partitions',
    start_date: '2026-08-01',
    end_date: '2026-09-30',
    planned_cost: 175000,
    actual_cost: 0,
    progress: 0,
    status: 'Not Started',
  },
  {
    id: 'wbs_act_4_1',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_4',
    is_phase: false,
    wbs_code: '04.01',
    name: 'External Walls & Damp Proof Course',
    description: 'Exterior insulated blockwork and weep vents',
    start_date: '2026-08-01',
    end_date: '2026-08-31',
    planned_cost: 95000,
    actual_cost: 0,
    progress: 0,
    status: 'Not Started',
  },
  {
    id: 'wbs_act_4_2',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_4',
    is_phase: false,
    wbs_code: '04.02',
    name: 'Internal Partition Walls',
    description: 'Acoustic masonry unit layout for unit separations',
    start_date: '2026-09-01',
    end_date: '2026-09-30',
    planned_cost: 80000,
    actual_cost: 0,
    progress: 0,
    status: 'Not Started',
  },

  // Phase 05: Finishing
  {
    id: 'wbs_phase_5',
    project_id: 'proj_act_1',
    parent_id: null,
    is_phase: true,
    phase_code: '05',
    wbs_code: '05',
    name: '05 — Finishing',
    description: 'Plastering, drylining, tile flooring, interior painting',
    start_date: '2026-10-01',
    end_date: '2026-11-25',
    planned_cost: 200000,
    actual_cost: 0,
    progress: 0,
    status: 'Not Started',
  },
  {
    id: 'wbs_act_5_1',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_5',
    is_phase: false,
    wbs_code: '05.01',
    name: 'Plastering & Skimming',
    description: 'Interior wall surface preparation and plaster finish',
    start_date: '2026-10-01',
    end_date: '2026-10-20',
    planned_cost: 70000,
    actual_cost: 0,
    progress: 0,
    status: 'Not Started',
  },
  {
    id: 'wbs_act_5_2',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_5',
    is_phase: false,
    wbs_code: '05.02',
    name: 'Flooring & Tiling',
    description: 'Ceramic tiling in wet areas and engineered oak flooring',
    start_date: '2026-10-21',
    end_date: '2026-11-10',
    planned_cost: 80000,
    actual_cost: 0,
    progress: 0,
    status: 'Not Started',
  },
  {
    id: 'wbs_act_5_3',
    project_id: 'proj_act_1',
    parent_id: 'wbs_phase_5',
    is_phase: false,
    wbs_code: '05.03',
    name: 'Interior & Exterior Painting',
    description: 'Primer and 2 coats low-VOC architectural paint',
    start_date: '2026-11-11',
    end_date: '2026-11-25',
    planned_cost: 50000,
    actual_cost: 0,
    progress: 0,
    status: 'Not Started',
  },
];

// Initial Cost Records for proj_act_1 (Total = 72400 + 206500 + 148100 = 427,000 CAD)
export const INITIAL_COSTS: CostRecord[] = [
  {
    id: 'cost_1',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_1_1',
    category: 'Other',
    description: 'Municipal construction site permit & hoarding clearance',
    amount: 14200,
    date: '2026-03-02',
    payee: 'City of Toronto Licensing',
    reference: 'PERM-2026-881',
    notes: 'Approved without variances',
    created_at: '2026-03-02T10:00:00Z',
  },
  {
    id: 'cost_2',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_1_1',
    category: 'Equipment',
    description: 'Site office trailer delivery, connection & security power drop',
    amount: 24000,
    date: '2026-03-05',
    payee: 'Ontario Mobile Structures Ltd',
    reference: 'INV-44910',
    notes: 'Net 30 terms',
    created_at: '2026-03-05T14:30:00Z',
  },
  {
    id: 'cost_3',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_1_2',
    category: 'Labour',
    description: 'Site safety orientation crew & perimeter fence installation',
    amount: 18500,
    date: '2026-03-12',
    payee: 'Direct Site Workforce Payroll',
    reference: 'PAY-W11-2026',
    notes: '8 workers over 10 days',
    created_at: '2026-03-12T16:00:00Z',
  },
  {
    id: 'cost_4',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_1_2',
    category: 'Materials',
    description: 'Anti-intrusion fencing panels and emergency eye-wash stations',
    amount: 15700,
    date: '2026-03-15',
    payee: 'BuildGuard Safety Supplies',
    reference: 'BG-9921',
    created_at: '2026-03-15T11:00:00Z',
  },
  {
    id: 'cost_5',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_2_1',
    category: 'Subcontractor',
    description: 'Hydraulic excavator bulk earthworks and soil cartage',
    amount: 64100,
    date: '2026-03-29',
    payee: 'Great Lakes Excavation Group',
    reference: 'GLE-3920',
    notes: 'Completed ahead of schedule',
    created_at: '2026-03-29T17:00:00Z',
  },
  {
    id: 'cost_6',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_2_2',
    category: 'Materials',
    description: 'Sub-slab bitumen blinding membrane and geo-textile drainage cloth',
    amount: 19800,
    date: '2026-04-10',
    payee: 'ProSeal Building Membranes',
    reference: 'PSM-1092',
    created_at: '2026-04-10T13:00:00Z',
  },
  {
    id: 'cost_7',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_2_2',
    category: 'Labour',
    description: 'Blinding levelling screed application labour',
    amount: 14000,
    date: '2026-04-16',
    payee: 'Direct Site Workforce Payroll',
    reference: 'PAY-W15-2026',
    created_at: '2026-04-16T15:00:00Z',
  },
  {
    id: 'cost_8',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_2_3',
    category: 'Materials',
    description: '45 tons 20mm & 25mm structural rebar ties and chairs',
    amount: 49800,
    date: '2026-04-26',
    payee: 'Stelco Steel Fabrication',
    reference: 'STEL-78902',
    created_at: '2026-04-26T10:30:00Z',
  },
  {
    id: 'cost_9',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_2_4',
    category: 'Materials',
    description: '35 MPa certified foundation slab concrete mix (18 mixer trucks)',
    amount: 42300,
    date: '2026-05-04',
    payee: 'Lafarge Concrete Canada',
    reference: 'LFG-44919',
    created_at: '2026-05-04T08:00:00Z',
  },
  {
    id: 'cost_10',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_2_4',
    category: 'Equipment',
    description: '42-meter boom pump rental and operating team for foundation pour',
    amount: 16500,
    date: '2026-05-06',
    payee: 'Precision Pump Services',
    reference: 'PPS-3301',
    created_at: '2026-05-06T18:00:00Z',
  },
  {
    id: 'cost_11',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_3_1',
    category: 'Subcontractor',
    description: 'Vertical column shuttering formwork and concrete pour',
    amount: 98400,
    date: '2026-06-08',
    payee: 'Apex Concrete & Forming Corp',
    reference: 'ACF-9901',
    created_at: '2026-06-08T15:20:00Z',
  },
  {
    id: 'cost_12',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_3_2',
    category: 'Labour',
    description: 'Level 2 beam shuttering carpentry team',
    amount: 22700,
    date: '2026-06-25',
    payee: 'Direct Site Workforce Payroll',
    reference: 'PAY-W25-2026',
    created_at: '2026-06-25T16:00:00Z',
  },
  {
    id: 'cost_13',
    project_id: 'proj_act_1',
    wbs_id: 'wbs_act_3_2',
    category: 'Materials',
    description: 'Plywood formwork panels, timber props, and steel walers',
    amount: 27000,
    date: '2026-07-02',
    payee: 'Rona Building Pro Solutions',
    reference: 'RON-8831',
    created_at: '2026-07-02T11:45:00Z',
  },
];

export const INITIAL_SITE_REPORTS: SiteReport[] = [
  {
    id: 'sr_1',
    project_id: 'proj_act_1',
    date: '2026-07-08',
    supervisor: 'David Chen',
    weather: 'Sunny',
    activities: 'Completed reinforcement cage tying for Level 2 perimeter beam framing. Pre-pour structural engineer inspection passed with zero defects.',
    workers: 18,
    materials: 'Received 12 bundles of 16mm rebar and 40 gallons of form-release oil.',
    issues: 'Brief 30-minute delay due to concrete pump traffic routing near Lakeshore Blvd.',
    safety_notes: 'Conducted mandatory 10-minute morning toolbox safety talk on fall protection harness inspection.',
    progress: 45,
    comments: 'Structural frame is tracking right on target with planned milestone schedule.',
    flag: 'delay',
    flag_reason: 'Brief 30-minute delay due to concrete pump traffic routing near Lakeshore Blvd.',
    email_alerts_sent: 1,
    last_alert_sent_at: '2026-07-08T17:35:00Z',
    alert_recipients: [
      {
        name: 'David Chen',
        email: 'david.chen@buildiq.ca',
        role: 'pm',
        sent_at: '2026-07-08T17:35:00Z',
      },
    ],
    photos: [
      {
        id: 'photo_1',
        site_report_id: 'sr_1',
        file_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f8?auto=format&fit=crop&w=800&q=80',
        caption: 'Level 2 beam shuttering inspection and steel rebar tie-off',
      },
      {
        id: 'photo_2',
        site_report_id: 'sr_1',
        file_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
        caption: 'North corner vertical column formwork alignment check',
      },
    ],
    created_at: '2026-07-08T17:30:00Z',
  },
  {
    id: 'sr_2',
    project_id: 'proj_act_1',
    date: '2026-06-20',
    supervisor: 'David Chen',
    weather: 'Clear',
    activities: 'Stripped column formwork on Level 1. Commenced scaffolding erection for suspended beam soffits.',
    workers: 16,
    materials: 'Modular scaffold standards and screw jacks unpacked on site.',
    issues: 'None reported.',
    safety_notes: 'Hardhats and high-visibility vests 100% compliant across all subtrades.',
    progress: 40,
    comments: 'Column concrete 7-day compressive break test results exceeded 38.5 MPa.',
    flag: 'normal',
    photos: [
      {
        id: 'photo_3',
        site_report_id: 'sr_2',
        file_url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=800&q=80',
        caption: 'Level 1 column curing and structural staging',
      },
    ],
    created_at: '2026-06-20T17:00:00Z',
  },
  {
    id: 'sr_3',
    project_id: 'proj_act_1',
    date: '2026-05-12',
    supervisor: 'David Chen',
    weather: 'Sunny',
    activities: 'Finalized foundation raft slab curing blankets and water spray protocol.',
    workers: 12,
    materials: 'Curing compound and moisture retention burlap.',
    issues: 'Minor rain shower previous night caused slight ponding, cleared with submersible pump.',
    safety_notes: 'Slip hazards mitigated promptly.',
    progress: 30,
    comments: 'Foundation milestone formally approved by municipal building inspector.',
    flag: 'normal',
    photos: [
      {
        id: 'photo_4',
        site_report_id: 'sr_3',
        file_url: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800&q=80',
        caption: 'Cured foundation slab ready for superstructure column layout',
      },
    ],
    created_at: '2026-05-12T16:45:00Z',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  id: 'set_default',
  company_name: 'BuildIQ Engineering & Construction Ltd.',
  currency: 'CAD',
  currency_symbol: 'C$',
  amber_threshold_percent: 5,
  red_threshold_percent: 10,
  updated_at: '2026-09-01T00:00:00Z',
};

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_1',
    user_id: 'usr_admin',
    user_name: 'Sarah Jenkins',
    action: 'System Initialized',
    entity: 'settings',
    entity_id: 'set_default',
    details: 'Loaded initial database schema, clients, and historical benchmark baselines.',
    timestamp: '2026-09-01T08:00:00Z',
  },
  {
    id: 'aud_2',
    user_id: 'usr_pm',
    user_name: 'David Chen',
    action: 'Cost Added',
    entity: 'cost',
    entity_id: 'cost_13',
    details: 'Recorded C$27,000 for Materials (Plywood formwork) under WBS 03.02 Beams & Lintels.',
    timestamp: '2026-07-02T11:45:00Z',
  },
  {
    id: 'aud_3',
    user_id: 'usr_pm',
    user_name: 'David Chen',
    action: 'Site Report Submitted',
    entity: 'site_report',
    entity_id: 'sr_1',
    details: 'Submitted daily report with 2 site photos. Project progress updated to 45%.',
    timestamp: '2026-07-08T17:30:00Z',
  },
  {
    id: 'aud_4',
    user_id: 'usr_admin',
    user_name: 'Sarah Jenkins',
    action: 'Project Completed',
    entity: 'history',
    entity_id: 'hist_6',
    details: 'Completed PRJ-2025-004 St. Clair Plaza. Archived C$1,160,000 final cost (C$1,450/m²).',
    timestamp: '2025-12-12T14:00:00Z',
  },
];

export const INITIAL_DOCUMENTS: ProjectDocument[] = [
  // Riverside Modern Condominiums (proj_act_1)
  {
    id: 'doc_1',
    project_id: 'proj_act_1',
    title: 'Architectural Working Drawings & Floor Plans (Rev C)',
    file_name: 'Riverside_Condo_Architectural_Working_Drawings_RevC.dwg',
    category: 'Blueprint',
    file_size: 18450000,
    file_type: 'application/acad',
    version: 'Rev C',
    status: 'Approved',
    uploaded_by: 'David Chen',
    uploaded_at: '2026-02-18T14:30:00Z',
    description: 'Complete architectural working drawing set including ground floor lobby, residential suites 101-312, building elevations, and roof assembly details.',
    issuing_authority: 'Quadrangle Architectural Associates',
    expiry_date: '2027-12-31',
    tags: ['Architecture', 'Floor Plans', 'Issued for Construction'],
  },
  {
    id: 'doc_2',
    project_id: 'proj_act_1',
    title: 'Municipal Building Permit — Superstructure & Deep Foundation',
    file_name: 'City_Toronto_Building_Permit_2026_BLD_0941.pdf',
    category: 'Permit',
    file_size: 2450000,
    file_type: 'application/pdf',
    version: 'v1.0',
    status: 'Active',
    uploaded_by: 'Sarah Jenkins',
    uploaded_at: '2026-02-24T09:15:00Z',
    description: 'Official municipal building permit issued under OBC 2024 covering foundation shoring, reinforced concrete core, and structural transfer slab.',
    issuing_authority: 'City of Toronto Buildings & Inspections Branch',
    expiry_date: '2027-02-28',
    tags: ['Permits', 'Municipal', 'Building Code'],
  },
  {
    id: 'doc_3',
    project_id: 'proj_act_1',
    title: 'Prime Construction Agreement — CCDC-2 Stipulated Price',
    file_name: 'Executed_CCDC2_Stipulated_Price_Contract_Riverside.pdf',
    category: 'Contract',
    file_size: 5120000,
    file_type: 'application/pdf',
    version: 'v1.0 (Executed)',
    status: 'Approved',
    uploaded_by: 'Elena Rostova',
    uploaded_at: '2026-02-20T11:00:00Z',
    description: 'Executed general construction contract outlining C$1,200,000 contract value, 10% statutory lien holdbacks, and monthly milestone claim terms.',
    issuing_authority: 'Apex Urban Developments & BuildSuite Group',
    expiry_date: '2026-11-30',
    tags: ['Contract', 'CCDC-2', 'Executed', 'Legal'],
  },
  {
    id: 'doc_4',
    project_id: 'proj_act_1',
    title: 'Structural Engineering Design Notes & Bar Bending Schedule',
    file_name: 'Riverside_Structural_Engineering_Calculations_Book.pdf',
    category: 'Specification',
    file_size: 9200000,
    file_type: 'application/pdf',
    version: 'Rev B',
    status: 'Approved',
    uploaded_by: 'David Chen',
    uploaded_at: '2026-03-05T16:20:00Z',
    description: '35 MPa concrete mix specifications, foundation shear-wall bar schedules, seismic transfer beam specifications, and cold-weather curing instructions.',
    issuing_authority: 'Entuitive Consulting Engineers Ltd.',
    tags: ['Structural', 'Concrete', 'Calculations'],
  },
  {
    id: 'doc_5',
    project_id: 'proj_act_1',
    title: 'Site-Specific Safety Plan & Emergency Response Protocol',
    file_name: 'Riverside_Site_Specific_Safety_Plan_OHSA.pdf',
    category: 'Safety & Compliance',
    file_size: 1850000,
    file_type: 'application/pdf',
    version: 'v2.1',
    status: 'Active',
    uploaded_by: 'David Chen',
    uploaded_at: '2026-03-01T08:00:00Z',
    description: 'Ontario Occupational Health & Safety Act compliant plan, crane swing safety clearances, excavation shoring audits, and weekly toolbox talk registry.',
    issuing_authority: 'BuildSuite Safety Board / WSIB Certified',
    expiry_date: '2026-11-30',
    tags: ['Safety', 'OHSA', 'WSIB', 'Emergency'],
  },
  {
    id: 'doc_6',
    project_id: 'proj_act_1',
    title: 'Mechanical & Electrical Coordinated Riser Diagrams (MEP)',
    file_name: 'Riverside_MEP_Mechanical_Electrical_Plumbing_RevB.pdf',
    category: 'Blueprint',
    file_size: 12300000,
    file_type: 'application/pdf',
    version: 'Rev B',
    status: 'Under Review',
    uploaded_by: 'David Chen',
    uploaded_at: '2026-04-12T13:45:00Z',
    description: 'Coordinated HVAC ductwork, heat recovery ventilation (ERV) shafts, domestic water risers, and 600V main electrical switchgear layouts.',
    issuing_authority: 'Smith + Andersen Mechanical Engineers',
    tags: ['MEP', 'HVAC', 'Electrical', 'Plumbing'],
  },

  // Centennial Corporate HQ Refit (proj_act_2)
  {
    id: 'doc_7',
    project_id: 'proj_act_2',
    title: 'Interior Alteration & Selective Demolition Permit #2026-DEMO-441',
    file_name: 'City_Ottawa_Demolition_Interior_Permit_441.pdf',
    category: 'Permit',
    file_size: 1980000,
    file_type: 'application/pdf',
    version: 'v1.0',
    status: 'Active',
    uploaded_by: 'Sarah Jenkins',
    uploaded_at: '2026-01-10T10:00:00Z',
    description: 'Authorized selective structural demolition permit covering asbestos abatement zones, core wall penetrations, and temporary egress provisions.',
    issuing_authority: 'City of Ottawa Building Code Services',
    expiry_date: '2026-10-15',
    tags: ['Permit', 'Demolition', 'Ottawa'],
  },
  {
    id: 'doc_8',
    project_id: 'proj_act_2',
    title: 'Master Commercial Refit & Tenant Fit-out Agreement',
    file_name: 'Centennial_Master_Tenant_Agreement_Executed.pdf',
    category: 'Contract',
    file_size: 4670000,
    file_type: 'application/pdf',
    version: 'v1.1',
    status: 'Approved',
    uploaded_by: 'Elena Rostova',
    uploaded_at: '2026-01-08T15:30:00Z',
    description: 'Prime commercial refit contract between Skyline Commercial Holdings and BuildSuite Contractors for full-floor modernization across 4 levels.',
    issuing_authority: 'Skyline Commercial Holdings Ltd.',
    expiry_date: '2026-09-15',
    tags: ['Contract', 'Commercial', 'Executed'],
  },
  {
    id: 'doc_9',
    project_id: 'proj_act_2',
    title: 'Levels 1-4 Open-Plan Architectural Floorplans (Rev D)',
    file_name: 'Centennial_Architectural_Floorplans_Levels1_4.dwg',
    category: 'Blueprint',
    file_size: 22100000,
    file_type: 'application/acad',
    version: 'Rev D',
    status: 'Approved',
    uploaded_by: 'Sarah Jenkins',
    uploaded_at: '2026-01-20T17:00:00Z',
    description: 'BIM-coordinated architectural layouts showing executive boardroom acoustics, demountable glass partitions, and raised access flooring.',
    issuing_authority: 'Perkins&Will Architects Ottawa',
    tags: ['Blueprints', 'Floorplans', 'BIM'],
  },

  // Centennial Corporate HQ Refit (proj_act_2) supplementary documentation
  {
    id: 'doc_10',
    project_id: 'proj_act_2',
    title: 'Commercial Development Approval & Environmental Compliance',
    file_name: 'Centennial_Development_Permit_2026.pdf',
    category: 'Permit',
    file_size: 3400000,
    file_type: 'application/pdf',
    version: 'v1.0',
    status: 'Active',
    uploaded_by: 'David Chen',
    uploaded_at: '2026-04-18T11:20:00Z',
    description: 'Commercial zoning approval including public realm setbacks, acoustic testing, and seismic refit clearances.',
    issuing_authority: 'City of Ottawa Planning Commission',
    expiry_date: '2027-04-30',
    tags: ['Permits', 'Commercial', 'Ottawa'],
  },
  {
    id: 'doc_11',
    project_id: 'proj_act_2',
    title: 'Double-Glazed Curtain Wall Engineering Specification',
    file_name: 'Centennial_Curtain_Wall_Acoustic_Specs.pdf',
    category: 'Specification',
    file_size: 6800000,
    file_type: 'application/pdf',
    version: 'v1.0',
    status: 'Under Review',
    uploaded_by: 'David Chen',
    uploaded_at: '2026-04-25T09:00:00Z',
    description: 'AAMA 501 test-compliant high-performance curtain wall glazing with argon thermal breaks, low-E solar coatings, and wind-load anchors.',
    issuing_authority: 'Kawneer Architectural Systems',
    tags: ['Specification', 'Curtain Wall', 'Glazing'],
  },

  // Bloor West Medical Pavilion (proj_plan_1)
  {
    id: 'doc_12',
    project_id: 'proj_plan_1',
    title: 'Institutional Zoning Variance & Transit Clearance Application',
    file_name: 'Bloor_Medical_Zoning_Variance_Permit_App.pdf',
    category: 'Permit',
    file_size: 4100000,
    file_type: 'application/pdf',
    version: 'Draft 1.1',
    status: 'Under Review',
    uploaded_by: 'Sarah Jenkins',
    uploaded_at: '2026-05-10T14:15:00Z',
    description: 'Variance application submitted for medical imaging suite floor loading, ambulance bay turning radii, and TTC subway line proximity assessment.',
    issuing_authority: 'Toronto Committee of Adjustment',
    tags: ['Zoning', 'Institutional', 'Application'],
  },
];

export const INITIAL_ALERTS: EmailAlert[] = [
  {
    id: 'alert_init_1',
    report_id: 'sr_1',
    project_id: 'proj_act_1',
    project_name: 'Riverside Modern Condominiums',
    project_number: 'PRJ-2026-001',
    flag: 'delay',
    recipient_name: 'David Chen',
    recipient_email: 'david.chen@buildiq.ca',
    recipient_role: 'pm',
    sender_name: 'David Chen',
    subject: '⚠️ [SCHEDULE DELAY ALERT] Riverside Modern Condominiums (PRJ-2026-001) - Milestone Variance Reported',
    body_html: `
<div style="font-family: sans-serif; padding: 20px; background: #fff; border: 1px solid #e2e8f0; border-radius: 8px;">
  <h2 style="color: #d97706; margin-top: 0;">⚠️ SCHEDULE DELAY ALERT</h2>
  <p><strong>Project:</strong> Riverside Modern Condominiums (PRJ-2026-001)</p>
  <p><strong>Site Supervisor:</strong> David Chen</p>
  <p><strong>Report Date:</strong> 2026-07-08</p>
  <div style="background: #fffbeb; padding: 12px; border-left: 4px solid #d97706; margin: 12px 0;">
    <strong>Issue:</strong> Brief 30-minute delay due to concrete pump traffic routing near Lakeshore Blvd.
  </div>
  <p>Recipient: David Chen &lt;david.chen@buildiq.ca&gt;</p>
</div>`.trim(),
    body_text: '[BUILDIQ NOTIFICATION SERVICE] DELAY ALERT\nProject: Riverside Modern Condominiums\nDate: 2026-07-08\nSupervisor: David Chen\nIssue: Brief 30-minute delay due to concrete pump traffic routing near Lakeshore Blvd.',
    status: 'delivered',
    created_at: '2026-07-08T17:35:00Z',
    sent_at: '2026-07-08T17:35:00Z',
    message_id: '<buildiq-alert_init_1@buildiq.ca>',
    metadata: {
      supervisor: 'David Chen',
      date: '2026-07-08',
      issues: 'Brief 30-minute delay due to concrete pump traffic routing near Lakeshore Blvd.',
      weather: 'Sunny',
      workers: 18,
    },
  },
];


